package io.daobab.example.springboot.blank;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/test")
public class Controller {

    //Inject here your DataBaseTarget generated by Daobab
//    private @Autowired
//    PizzaDataBase db;



    @GetMapping("/t01")
    public String t01(){
        return "this is test t01";
    }

    @GetMapping("/t02")
    public String t02(){
        return "this is test t02";
    }

    @GetMapping("/t03")
    public String t03(){
        return "this is test t03";
    }

    @GetMapping("/t04")
    public String t04(){
        return "this is test t04";
    }


    @GetMapping("/t05")
    public String t05(){
        return "this is test t05";
    }
}
